-- Create table for storing hidden items preference per household
create table if not exists household_item_hidden (
    id bigint generated by default as identity primary key,
    household_code text not null,
    item_id bigint not null references items(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(household_code, item_id)
);

-- Add index for performance
create index if not exists idx_household_item_hidden_lookup 
on household_item_hidden(household_code, item_id);

-- Enable RLS (Optional, mirroring existing structure)
alter table household_item_hidden enable row level security;

-- Policy: Allow all access for now (since we use a shared logic)
create policy "Allow full access to household_item_hidden"
on household_item_hidden for all
using (true)
with check (true);
